#!/bin/sh

P=`basename $0`
ACL=$HOMEMWC/autoconf/aclocal.m4
HERE=`pwd`

die() {
   echo "$P: $1"
   exit 1
}

warn() {
   echo "$P: $1"
}

. PACKAGES.sh

test -f $ACL || die "Master aclocal.m4 file $ACL does not exist!!"

for pack in $PACKAGES; do
   if test -d $pack; then
      cd $pack
      if test ! -L aclocal.m4; then
         warn "symbolic link $pack/aclocal.m4 does not exist ... linking from $ACL."
         test -f aclocal.m4 && rm aclocal.m4
         ln -s $ACL .
      else
         warn "symbolic link $pack/aclocal.m4 already exists."
      fi
      ls -l aclocal.m4
      sleep 1
      autoconf
      cd $HERE
   fi
done
Exp -n $PACKAGES
Exp rnpletal
