/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "rvs.h"
#include <malloc/malloc.h> //Modified by Lorenzo Rossi to be able to compile on Mac OS High Sierra. Originally it used to be #include <malloc.h>

bool_t
xdr_RVS1INT_args(xdrs, objp)
	XDR *xdrs;
	RVS1INT_args *objp;
{
	if (!xdr_int(xdrs, &objp->arg1)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVS2INT_args(xdrs, objp)
	XDR *xdrs;
	RVS2INT_args *objp;
{
	if (!xdr_int(xdrs, &objp->arg1)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->arg2)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVS3INT_args(xdrs, objp)
	XDR *xdrs;
	RVS3INT_args *objp;
{
	if (!xdr_int(xdrs, &objp->arg1)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->arg2)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->arg3)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSMXY1_args(xdrs, objp)
	XDR *xdrs;
	RVSMXY1_args *objp;
{
	if (!xdr_int(xdrs, &objp->wt)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->start.start_val, (u_int *)&objp->start.start_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->time.time_val, (u_int *)&objp->time.time_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nvec)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSMXYNT_args(xdrs, objp)
	XDR *xdrs;
	RVSMXYNT_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->start.start_val, (u_int *)&objp->start.start_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->time.time_val, (u_int *)&objp->time.time_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nvec)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSSTRING_args(xdrs, objp)
	XDR *xdrs;
	RVSSTRING_args *objp;
{
	if (!xdr_string(xdrs, &objp->vs_string, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSXN_args(xdrs, objp)
	XDR *xdrs;
	RVSXN_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSXNT_args(xdrs, objp)
	XDR *xdrs;
	RVSXNT_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSXY1_args(xdrs, objp)
	XDR *xdrs;
	RVSXY1_args *objp;
{
	if (!xdr_int(xdrs, &objp->wt)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSXY2_args(xdrs, objp)
	XDR *xdrs;
	RVSXY2_args *objp;
{
	if (!xdr_int(xdrs, &objp->wt)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->tag)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSXYNT_args(xdrs, objp)
	XDR *xdrs;
	RVSXYNT_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSXYTAGNT_args(xdrs, objp)
	XDR *xdrs;
	RVSXYTAGNT_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->tag.tag_val, (u_int *)&objp->tag.tag_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSSXYNT_args(xdrs, objp)
	XDR *xdrs;
	RVSSXYNT_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSXYN_args(xdrs, objp)
	XDR *xdrs;
	RVSXYN_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSGNXYNI_args(xdrs, objp)
	XDR *xdrs;
	RVSGNXYNI_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->index)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSGXYNI_args(xdrs, objp)
	XDR *xdrs;
	RVSGXYNI_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->index)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSNSCT_args(xdrs, objp)
	XDR *xdrs;
	RVSNSCT_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->sc)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->time)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_rxyvec0(xdrs, objp)
	XDR *xdrs;
	rxyvec0 *objp;
{
	if (!xdr_int(xdrs, &objp->index)) {
		return (FALSE);
	}
	if (!xdr_double(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->tag)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->n)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_rget_xyvec0_res(xdrs, objp)
	XDR *xdrs;
	rget_xyvec0_res *objp;
{
	if (!xdr_int(xdrs, &objp->errno)) {
		return (FALSE);
	}
	switch (objp->errno) {
	case 0:
		if (!xdr_rxyvec0(xdrs, &objp->rget_xyvec0_res_u.the_rxyvec0)) {
			return (FALSE);
		}
		break;
	}
	return (TRUE);
}

bool_t
xdr_RVSGETPARAMETERN_args(xdrs, objp)
	XDR *xdrs;
	RVSGETPARAMETERN_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->which_parameter)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSGETLXYN_args(xdrs, objp)
	XDR *xdrs;
	RVSGETLXYN_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_RVSGXYNALL_args(xdrs, objp)
	XDR *xdrs;
	RVSGXYNALL_args *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_rxyalldata0(xdrs, objp)
	XDR *xdrs;
	rxyalldata0 *objp;
{
	if (!xdr_string(xdrs, &objp->name, ~0)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nIndex)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nEvents)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->N.N_val, (u_int *)&objp->N.N_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->Time.Time_val, (u_int *)&objp->Time.Time_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->x.x_val, (u_int *)&objp->x.x_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->y.y_val, (u_int *)&objp->y.y_len, ~0, sizeof(double), (xdrproc_t) xdr_double)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_rget_xyalldata0_res(xdrs, objp)
	XDR *xdrs;
	rget_xyalldata0_res *objp;
{
	if (!xdr_int(xdrs, &objp->errno)) {
		return (FALSE);
	}
	switch (objp->errno) {
	case 0:
		if (!xdr_rxyalldata0(xdrs, &objp->rget_xyalldata0_res_u.the_rxyalldata0)) {
			return (FALSE);
		}
		break;
	}
	return (TRUE);
}
