/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <bstring.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <stdio.h>
#include <rpc/rpc.h>
#include <rpc/pmap_clnt.h>
#include "rvs.h"
#include <malloc.h>

static void rvs_1();

main()
{
	register SVCXPRT *transp;

	(void) pmap_unset(RVS, RVSVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf(stderr, "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RVS, RVSVERS, rvs_1, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (RVS, RVSVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf(stderr, "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RVS, RVSVERS, rvs_1, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (RVS, RVSVERS, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "svc_run returned");
	exit(1);
	/* NOTREACHED */
}

static void
rvs_1(rqstp, transp)
	struct svc_req *rqstp;
	SVCXPRT *transp;
{
	union __svcargun {
		RVSSTRING_args rvsopen_1_arg;
		RVSXY1_args rvsxy1_1_arg;
		RVSXY2_args rvsxy2_1_arg;
		RVS1INT_args rvsclose_1_arg;
		RVS1INT_args rvsstatus_1_arg;
		RVS2INT_args rvssetmaxlxy_1_arg;
		RVS2INT_args rvsgetparameter_1_arg;
		RVS3INT_args rvssetparameter_1_arg;
		RVS2INT_args rvssetaf_1_arg;
		RVS1INT_args rvssetthin_1_arg;
		RVSSTRING_args rvsnameq_1_arg;
		RVS1INT_args rvsglt_1_arg;
		RVSXYN_args rvsxyn_1_arg;
		RVSXYNT_args rvsxynt_1_arg;
		RVSXN_args rvsxn_1_arg;
		RVSXNT_args rvsxnt_1_arg;
		RVSSXYNT_args rvssxynt_1_arg;
		RVSMXYNT_args rvsmxynt_1_arg;
		RVSMXY1_args rvsmxy1_1_arg;
		RVSGNXYNI_args rvsgnxyni_1_arg;
		RVSNSCT_args rvsnsct_1_arg;
		RVSGXYNI_args rvsgxyni_1_arg;
		RVSGETPARAMETERN_args rvsgetparametern_1_arg;
		RVSGETLXYN_args rvsgetlxyn_1_arg;
		RVSGETLXYN_args rvsgxynall_1_arg;
		RVSXYTAGNT_args rvsxytagnt_1_arg;
	} argument;
	char *result;
	bool_t (*xdr_argument)(), (*xdr_result)();
	char *(*local)();

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case RVSCONNECT:
		xdr_argument = (xdrproc_t)xdr_void;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsconnect_1;
		break;

	case RVSOPEN:
		xdr_argument = (xdrproc_t)xdr_RVSSTRING_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsopen_1;
		break;

	case RVSXY1:
		xdr_argument = (xdrproc_t)xdr_RVSXY1_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsxy1_1;
		break;

	case RVSXY2:
		xdr_argument = (xdrproc_t)xdr_RVSXY2_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsxy2_1;
		break;

	case RVSCLOSE:
		xdr_argument = (xdrproc_t)xdr_RVS1INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsclose_1;
		break;

	case RVSHANG:
		xdr_argument = (xdrproc_t)xdr_void;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvshang_1;
		break;

	case RVSSTATUS:
		xdr_argument = (xdrproc_t)xdr_RVS1INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsstatus_1;
		break;

	case RVSGETVSPID:
		xdr_argument = (xdrproc_t)xdr_void;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsgetvspid_1;
		break;

	case RVSRESET:
		xdr_argument = (xdrproc_t)xdr_void;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsreset_1;
		break;

	case RVSSETMAXLXY:
		xdr_argument = (xdrproc_t)xdr_RVS2INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvssetmaxlxy_1;
		break;

	case RVSGETPARAMETER:
		xdr_argument = (xdrproc_t)xdr_RVS2INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsgetparameter_1;
		break;

	case RVSSETPARAMETER:
		xdr_argument = (xdrproc_t)xdr_RVS3INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvssetparameter_1;
		break;

	case RVSSETAF:
		xdr_argument = (xdrproc_t)xdr_RVS2INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvssetaf_1;
		break;

	case RVSSETTHIN:
		xdr_argument = (xdrproc_t)xdr_RVS1INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvssetthin_1;
		break;

	case RVSNAMEQ:
		xdr_argument = (xdrproc_t)xdr_RVSSTRING_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsnameq_1;
		break;

	case RVSGLT:
		xdr_argument = (xdrproc_t)xdr_RVS1INT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsglt_1;
		break;

	case RVSXYN:
		xdr_argument = (xdrproc_t)xdr_RVSXYN_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsxyn_1;
		break;

	case RVSXYNT:
		xdr_argument = (xdrproc_t)xdr_RVSXYNT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsxynt_1;
		break;

	case RVSXN:
		xdr_argument = (xdrproc_t)xdr_RVSXN_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsxn_1;
		break;

	case RVSXNT:
		xdr_argument = (xdrproc_t)xdr_RVSXNT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsxnt_1;
		break;

	case RVSSXYNT:
		xdr_argument = (xdrproc_t)xdr_RVSSXYNT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvssxynt_1;
		break;

	case RVSMXYNT:
		xdr_argument = (xdrproc_t)xdr_RVSMXYNT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsmxynt_1;
		break;

	case RVSMXY1:
		xdr_argument = (xdrproc_t)xdr_RVSMXY1_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsmxy1_1;
		break;

	case RVSGNXYNI:
		xdr_argument = (xdrproc_t)xdr_RVSGNXYNI_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsgnxyni_1;
		break;

	case RVSNSCT:
		xdr_argument = (xdrproc_t)xdr_RVSNSCT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsnsct_1;
		break;

	case RVSGXYNI:
		xdr_argument = (xdrproc_t)xdr_RVSGXYNI_args;
		xdr_result = (xdrproc_t)xdr_rget_xyvec0_res;
		local = (char *(*)()) rvsgxyni_1;
		break;

	case RVSGETPARAMETERN:
		xdr_argument = (xdrproc_t)xdr_RVSGETPARAMETERN_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsgetparametern_1;
		break;

	case RVSGETLXYN:
		xdr_argument = (xdrproc_t)xdr_RVSGETLXYN_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsgetlxyn_1;
		break;

	case RVSGXYNALL:
		xdr_argument = (xdrproc_t)xdr_RVSGETLXYN_args;
		xdr_result = (xdrproc_t)xdr_rget_xyalldata0_res;
		local = (char *(*)()) rvsgxynall_1;
		break;

	case RVSXYTAGNT:
		xdr_argument = (xdrproc_t)xdr_RVSXYTAGNT_args;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvsxytagnt_1;
		break;

	case RVSKILLALL:
		xdr_argument = (xdrproc_t)xdr_void;
		xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)()) rvskillall_1;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	bzero((char *)&argument, sizeof(argument));
	if (!svc_getargs(transp, xdr_argument, &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, &argument)) {
		fprintf(stderr, "unable to free arguments");
		exit(1);
	}
	return;
}
