/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <bstring.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <rpc/rpc.h>
#include <sys/time.h>
#include "rvs.h"
#include <malloc/malloc.h> //Modified by Lorenzo Rossi to be able to compile on Mac OS High Sierra. Originally it used to be #include <malloc.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
rvsconnect_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSCONNECT, (xdrproc_t)xdr_void, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsopen_1(argp, clnt)
	RVSSTRING_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSOPEN, (xdrproc_t)xdr_RVSSTRING_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsxy1_1(argp, clnt)
	RVSXY1_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSXY1, (xdrproc_t)xdr_RVSXY1_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsxy2_1(argp, clnt)
	RVSXY2_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSXY2, (xdrproc_t)xdr_RVSXY2_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsclose_1(argp, clnt)
	RVS1INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSCLOSE, (xdrproc_t)xdr_RVS1INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvshang_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSHANG, (xdrproc_t)xdr_void, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsstatus_1(argp, clnt)
	RVS1INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSSTATUS, (xdrproc_t)xdr_RVS1INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsgetvspid_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGETVSPID, (xdrproc_t)xdr_void, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsreset_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSRESET, (xdrproc_t)xdr_void, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvssetmaxlxy_1(argp, clnt)
	RVS2INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSSETMAXLXY, (xdrproc_t)xdr_RVS2INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsgetparameter_1(argp, clnt)
	RVS2INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGETPARAMETER, (xdrproc_t)xdr_RVS2INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvssetparameter_1(argp, clnt)
	RVS3INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSSETPARAMETER, (xdrproc_t)xdr_RVS3INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvssetaf_1(argp, clnt)
	RVS2INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSSETAF, (xdrproc_t)xdr_RVS2INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvssetthin_1(argp, clnt)
	RVS1INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSSETTHIN, (xdrproc_t)xdr_RVS1INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsnameq_1(argp, clnt)
	RVSSTRING_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSNAMEQ, (xdrproc_t)xdr_RVSSTRING_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsglt_1(argp, clnt)
	RVS1INT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGLT, (xdrproc_t)xdr_RVS1INT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsxyn_1(argp, clnt)
	RVSXYN_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSXYN, (xdrproc_t)xdr_RVSXYN_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsxynt_1(argp, clnt)
	RVSXYNT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSXYNT, (xdrproc_t)xdr_RVSXYNT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsxn_1(argp, clnt)
	RVSXN_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSXN, (xdrproc_t)xdr_RVSXN_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsxnt_1(argp, clnt)
	RVSXNT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSXNT, (xdrproc_t)xdr_RVSXNT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvssxynt_1(argp, clnt)
	RVSSXYNT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSSXYNT, (xdrproc_t)xdr_RVSSXYNT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsmxynt_1(argp, clnt)
	RVSMXYNT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSMXYNT, (xdrproc_t)xdr_RVSMXYNT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsmxy1_1(argp, clnt)
	RVSMXY1_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSMXY1, (xdrproc_t)xdr_RVSMXY1_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsgnxyni_1(argp, clnt)
	RVSGNXYNI_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGNXYNI, (xdrproc_t)xdr_RVSGNXYNI_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsnsct_1(argp, clnt)
	RVSNSCT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSNSCT, (xdrproc_t)xdr_RVSNSCT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

rget_xyvec0_res *
rvsgxyni_1(argp, clnt)
	RVSGXYNI_args *argp;
	CLIENT *clnt;
{
	static rget_xyvec0_res res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGXYNI, (xdrproc_t)xdr_RVSGXYNI_args, argp, (xdrproc_t)xdr_rget_xyvec0_res, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsgetparametern_1(argp, clnt)
	RVSGETPARAMETERN_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGETPARAMETERN, (xdrproc_t)xdr_RVSGETPARAMETERN_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsgetlxyn_1(argp, clnt)
	RVSGETLXYN_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGETLXYN, (xdrproc_t)xdr_RVSGETLXYN_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

rget_xyalldata0_res *
rvsgxynall_1(argp, clnt)
	RVSGETLXYN_args *argp;
	CLIENT *clnt;
{
	static rget_xyalldata0_res res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSGXYNALL, (xdrproc_t)xdr_RVSGETLXYN_args, argp, (xdrproc_t)xdr_rget_xyalldata0_res, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvsxytagnt_1(argp, clnt)
	RVSXYTAGNT_args *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSXYTAGNT, (xdrproc_t)xdr_RVSXYTAGNT_args, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}

int *
rvskillall_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static int res;

	bzero((char *)&res, sizeof(res));
	if (clnt_call(clnt, RVSKILLALL, (xdrproc_t)xdr_void, argp, (xdrproc_t)xdr_int, &res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&res);
}
