      external         dvvm

      external         dvvd

      external         dvvdx

      external         dvva

      external         dvvs

      external         dvsm

      external         dvsa

      external         dvls

      external         dvneg

      external         dvfapl

      double precision dminus
      external         dminus

      double precision drecip
      external         drecip

      double precision ldexp
      external         ldexp

      external         dvramp

      external         dvcopy

      external         dvrev

      external         dvrevp

      external         dvextr

      external         dvsd

      external         dvinq1

      external         dvinq2

      external         dvdd1

      external         dvav

      external         dvvsm

      external         dvvasm

      external         dvvssm

      external         dvsvsa

      external         dvabd

      external         dvabrd

      external         dvrd

      external         dvconc

      double precision dvvdot
      external         dvvdot

      external         dvvprj

      double precision dvsum
      external         dvsum

      double precision dvmean
      external         dvmean

      external         dvdevm

      double precision dvsuma
      external         dvsuma

      external         dvdupr

      external         dvdup

      external         dvdd01

      external         dvdd02

      external         dvinj

      external         dvinju

      external         dvsvva

      external         dvsvvs

      external         dvdd1g

      external         dvdd2g

      external         dvpms

      double precision dvnrm2
      external         dvnrm2

      double precision dvnrm1
      external         dvnrm1

      external         dvliq1

      external         dvcuq1

      double precision ngfpq3
      external         ngfpq3

      integer          idvmcx
      external         idvmcx

      integer          idvmcv
      external         idvmcv

      integer          idvxtr
      external         idvxtr

      logical          pibetw
      external         pibetw

      external         dvcopr

      external         dvrsh

      external         dvlsh

      external         dvucrsh

      external         dvuclsh

      external         dvnull

      integer          idvfne
      external         idvfne

      external         dvciq1

      external         dvd2q1

      external         dvd2q2

      external         dvd2q3

      integer          idroun
      external         idroun

      external         dd02q2

      external         dnoiz1

      external         dvfap2

      double precision dpowr
      external         dpowr

      double precision dvmin
      external         dvmin

      double precision dvminnz
      external         dvminnz

      double precision dvmax
      external         dvmax

      integer          idvmin
      external         idvmin

      integer          idvmax
      external         idvmax

      double precision dvlinf
      external         dvlinf

      external         dvsmth

      external         dvgaus

      external         dvmrg

      external         dvumrg

      external         dvvarr

      external         dvdump

      external         dvdmpx

      external         dvpdmp

      external         dvdmp1

      integer          idvscn
      external         idvscn

      external         dvinq3

      double precision flip2
      external         flip2

      external         dvinq4

      double precision flip3
      external         flip3

      external         dvinqn

      logical          leven
      external         leven

      external         dvinq2n

      integer          llogic
      external         llogic

      double precision flipn
      external         flipn

      external         dvicps

      external         dvlcps

      external         dvcpyi

      external         dvrex

      external         dvpyth

      external         dvsofs

      external         dvdofs

      external         dvavvm

      external         dvsvvm

      double precision mu
      external         mu

      external         dvgesc

      external         dvchtn

      external         dvsngl

      external         dvdoub

      external         dvi4q1

      external         dvi4qv

      external         dvoutu

      external         dvinu

      external         dvrng

      external         dvorng

      external         dvarc1

      external         dvggpr

      external         dvgrq1

      integer          lnintd
      external         lnintd

      double precision dnintd
      external         dnintd

      double precision ldlog2
      external         ldlog2

      integer          lilog2
      external         lilog2

      logical          lp2np1
      external         lp2np1

      logical          lp2n
      external         lp2n

      external         dvglmf

      external         dvtnug

      external         dvd1nu

      external         dvd0t0

      external         dvddt1

      external         dvavt0

      external         dvd22

      external         dvdd22

      external         dvd2t0

      external         dvde0

      external         dvdde0

      external         dvplsl

      external         dvinle

      external         dvinre

      external         dvrmpl

      external         dvthin

      external         dvthin_bbox

      external         dvclp1

      integer          idvllm
      external         idvllm

      integer          ixvinf
      external         ixvinf

      external         nrmmes

      external         dvprln

      external         dvav2

      external         dviscl

      double precision dvhash
      external         dvhash

      external         dout

      double precision dvcasp
      external         dvcasp

      external         dvpwri

      external         dvprea

      external         dvpwri1

      external         dvpwri1f

      external         dvprea1

      external         dvwri1

      external         dvrea1

      external         dvtwri1

      external         dvp_dump

      external         dvp_load

      integer          ix_clip_min
      external         ix_clip_min

      integer          ix_clip_max
      external         ix_clip_max

      integer          ixminf
      external         ixminf

      integer          ixmaxf
      external         ixmaxf

      external         dvmimk

      external         dvuimk

      external         dvmlmk

      external         dvulmk

      integer          idvscf
      external         idvscf

      external         dvthpl

      double precision dotarg
      external         dotarg

      external         dvinex

      external         dvinexf

      external         dvrflc

      logical          isu1g
      external         isu1g

      integer          iisu1g
      external         iisu1g

      external         dvlntb

      external         dvrsd

      external         dvlt

      external         dvxyun

      external         dvxun

      integer          ixminf_slow
      external         ixminf_slow

      integer          ixmaxf_slow
      external         ixmaxf_slow

      integer          ix_clip_min_slow
      external         ix_clip_min_slow

      integer          ix_clip_max_slow
      external         ix_clip_max_slow

      external         dvfilt

      double precision dcheby
      external         dcheby

      double precision dcheb1
      external         dcheb1

      external         dvcheb

      double precision dvtrap
      external         dvtrap

      double precision dvtrpc
      external         dvtrpc

      double precision dleg
      external         dleg

      external         dvleg

      logical          drange
      external         drange

      external         dvechb

      external         dveleg

      external         dvchft

      external         dvleft

      double precision dvdmin
      external         dvdmin

      double precision dvdmax
      external         dvdmax

      double precision dvxtrap1
      external         dvxtrap1

      external         dvleftx

      external         dvchftx

      external         techek

      integer          isdvmono
      external         isdvmono

      external         dvmchft

      external         dvmechb

      external         dvlnt

      external         dvsig

      external         dvsig0

      external         dvdsig

      external         axseg0

      external         dvchbdc

      external         dvmchbdc

      external         dvchbdnc

      external         dvmchbdnc

      external         dvmofa

      external         dvedtl

      external         dvedhd

      external         dvaofm

      external         dvct1

      external         dvmofxy

      external         dvppfx

      external         dvpify

      double precision dqfit
      external         dqfit

      external         dvmint

      external         dvrmint

      external         dvlofa

      external         dvpbc

      logical          haspbc
      external         haspbc

      integer          nnpbc
      external         nnpbc

      double precision dvuti
      external         dvuti

      external         dvrolldown

      external         dvrollup

      external         dvrollboth

      external         dvxycv

      external         dvcfar

      external         dvchebdn

      integer          dvchmcft
      external         dvchmcft

      external         dvnestcfdn

      external         dvxycvs

      external         dv2wt1

      external         daub4

      external         dv2daub4f

      external         dv2daub4r

      external         dvdaub4r

      external         dvdaub4f

      external         dvthresh

      external         lfour1

      external         lrft

      external         dv2rfftf

      external         dv2rfftr

      external         dvfftr

      external         dvfftf

      external         dvfftm

      external         dvumsh

      external         dvgmsh

      external         dvvdxx

      external         dvnpyth

      external         dvzeta_of_phi

      external         dvkappa_of_ph_pp_zeta

      double precision dvamax
      external         dvamax

      external         dv2i4

      external         dvsma4

      external         dvsavm

      external         dvpoly

      external         dvcf2

      external         dvcf4

      external         dvumfcn

      external         dvpowtr

      external         dvvpowtr

      double precision fdvinqn
      external         fdvinqn

      double precision clls
      external         clls

      external         dvlls

      external         dvdlls

      external         cmposo

      logical          rngfuzz
      external         rngfuzz

      double precision fdvumint
      external         fdvumint

      double precision uflipn
      external         uflipn

      external         dvquadexf

      external         dvquadexb

      external         dvquadex

      external         dvbcopy

      external         dvlocmx

      external         dvlocmn

      external         quadex

      external         dvscale

      external         dvtanhremap

      external         dvhsex2

      external         dvhsex4

      external         dvfsex2

      external         dvfsex4

      double precision dvmaxrd
      external         dvmaxrd

