      external         dvi2q1

      external         dvmask

      external         dvextrema

      external         dvd1

      external         dvumesh

      external         dvdd1nu

      double precision dvvcos
      external         dvvcos

      double precision dvvpears
      external         dvvpears

      external         dvllsfull

      external         dvsglmf

      external         dvabs

      external         dvlog10

      external         dvtwri1f

      external         dvgauspbc

      external         dvpbcextend

      external         dvpbcset

      logical          haspbcp
      external         haspbcp

      external         dvpbcdelete

      external         dvpbcconvert

      external         dvextremacons

      external         dvqfit

      external         dvinqn_fuzz

      external         dvvadf

      external         dvmint_dx_sense

      external         dvrmint_dx_sense

      external         dx_state_reset

      logical          dx_state_changed
      external         dx_state_changed

      logical          dx_state_0
      external         dx_state_0

      external         dvrshw

      external         dvlint

      external         dvlbs

      external         dvsaw

      double precision fdvx0
      external         fdvx0

      external         dvx0

      double precision dvvsum
      external         dvvsum

      external         dvstridecopy

      external         dvc2tos2x

      external         dvc2tos2y

      external         dvc2tos2z

      integer          idvsortstate
      external         idvsortstate

      real             *8 dvqfitres
      external         *8 dvqfitres

      external         dvgtanhkink

      external         dvyxby1mx

      external         dvdv

      external         dvdkv

      external         dvminima

      external         dvmaxima

