      external         ivvm

      external         ivvd

      external         ivva

      external         ivvs

      external         ivsm

      external         ivsa

      external         ivls

      external         ivneg

      integer          ivmin
      external         ivmin

      integer          ivmax
      external         ivmax

      external         ivfapl

      external         ivramp

      external         ivrmp2

      external         ivcopy

      external         ivrev

      integer          ivcnts
      external         ivcnts

      logical          pivza
      external         pivza

      integer          ivsum
      external         ivsum

      integer          ivindx
      external         ivindx

      external         ivdump

      external         ivpdmp

      external         ivdmp1

      external         ivinj

      external         ivwri1

      external         ivrea1

      integer          ivprimedecomp
      external         ivprimedecomp

      integer          ivprod
      external         ivprod

      external         ivdiff1

