      external         svvm

      external         svvd

      external         svva

      external         svvs

      external         svsm

      external         svsa

      external         svls

      external         svneg

      external         svfapl

      external         svramp

      external         svcopy

      external         svrev

      external         svextr

      external         svsd

      external         svinq1

      external         svinq2

      external         svdd1

      external         svav

      external         svvsm

      external         svvasm

      external         svsvsa

      external         svabd

      external         svabrd

      external         svconc

      real             svvdot
      external         svvdot

      external         svvprj

      real             svsum
      external         svsum

      external         svdupr

      external         svdup

      external         svvd0

      external         svinj

      real             svnrm2
      external         svnrm2

      integer          isvcls
      external         isvcls

      real             svmin
      external         svmin

      real             svmax
      external         svmax

      integer          isvmin
      external         isvmin

      integer          isvmax
      external         isvmax

      external         svsngl

      external         svdump

      external         svlmap

      external         svthin

      external         svrng

      external         sviscl

      external         svpyth

      external         svavvm

      integer          myisamax
      external         myisamax

