/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rvs.h"
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

#ifdef DEBUG
#define RPC_SVC_FG
#endif

#define _RPCSVC_CLOSEDOWN 120
#include <stdlib.h>
#include <string.h> //added by LR - new compilers seem to require this
static int _rpcpmstart;		/* Started by a port monitor ? */
static int _rpcfdtype;		/* Whether Stream or Datagram ? */
static int _rpcsvcdirty;	/* Still serving ? */

static
void _msgout(msg)
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, "%s", msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, "%s", msg);
#endif
}

static void
closedown()
{
	if (_rpcsvcdirty == 0) {
		extern fd_set svc_fdset;
		static int size;
		int i, openfd;

		if (_rpcfdtype == SOCK_DGRAM)
			exit(0);
		if (size == 0) {
			size = getdtablesize();
		}
		for (i = 0, openfd = 0; i < size && openfd < 2; i++)
			if (FD_ISSET(i, &svc_fdset))
				openfd++;
		if (openfd <= (_rpcpmstart?0:1))
			exit(0);
	}
	(void) alarm(_RPCSVC_CLOSEDOWN);
}

static void
rvs_1(rqstp, transp)
	struct svc_req *rqstp;
	SVCXPRT *transp;
{
	union {
		RVSSTRING_args rvsopen_1_arg;
		RVSXY1_args rvsxy1_1_arg;
		RVSXY2_args rvsxy2_1_arg;
		RVS1INT_args rvsclose_1_arg;
		RVS1INT_args rvsstatus_1_arg;
		RVS2INT_args rvssetmaxlxy_1_arg;
		RVS2INT_args rvsgetparameter_1_arg;
		RVS3INT_args rvssetparameter_1_arg;
		RVS2INT_args rvssetaf_1_arg;
		RVS1INT_args rvssetthin_1_arg;
		RVSSTRING_args rvsnameq_1_arg;
		RVS1INT_args rvsglt_1_arg;
		RVSXYN_args rvsxyn_1_arg;
		RVSXYNT_args rvsxynt_1_arg;
		RVSXN_args rvsxn_1_arg;
		RVSXNT_args rvsxnt_1_arg;
		RVSSXYNT_args rvssxynt_1_arg;
		RVSMXYNT_args rvsmxynt_1_arg;
		RVSMXY1_args rvsmxy1_1_arg;
		RVSGNXYNI_args rvsgnxyni_1_arg;
		RVSNSCT_args rvsnsct_1_arg;
		RVSGXYNI_args rvsgxyni_1_arg;
		RVSGETPARAMETERN_args rvsgetparametern_1_arg;
		RVSGETLXYN_args rvsgetlxyn_1_arg;
		RVSGETLXYN_args rvsgxynall_1_arg;
		RVSXYTAGNT_args rvsxytagnt_1_arg;
	} argument;
	char *result;
	bool_t (*xdr_argument)(), (*xdr_result)();
	char *(*local)();

	_rpcsvcdirty = 1;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		_rpcsvcdirty = 0;
		return;

	case RVSCONNECT:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsconnect_1_svc;
		break;

	case RVSOPEN:
		xdr_argument = xdr_RVSSTRING_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsopen_1_svc;
		break;

	case RVSXY1:
		xdr_argument = xdr_RVSXY1_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsxy1_1_svc;
		break;

	case RVSXY2:
		xdr_argument = xdr_RVSXY2_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsxy2_1_svc;
		break;

	case RVSCLOSE:
		xdr_argument = xdr_RVS1INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsclose_1_svc;
		break;

	case RVSHANG:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) rvshang_1_svc;
		break;

	case RVSSTATUS:
		xdr_argument = xdr_RVS1INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsstatus_1_svc;
		break;

	case RVSGETVSPID:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsgetvspid_1_svc;
		break;

	case RVSRESET:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsreset_1_svc;
		break;

	case RVSSETMAXLXY:
		xdr_argument = xdr_RVS2INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvssetmaxlxy_1_svc;
		break;

	case RVSGETPARAMETER:
		xdr_argument = xdr_RVS2INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsgetparameter_1_svc;
		break;

	case RVSSETPARAMETER:
		xdr_argument = xdr_RVS3INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvssetparameter_1_svc;
		break;

	case RVSSETAF:
		xdr_argument = xdr_RVS2INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvssetaf_1_svc;
		break;

	case RVSSETTHIN:
		xdr_argument = xdr_RVS1INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvssetthin_1_svc;
		break;

	case RVSNAMEQ:
		xdr_argument = xdr_RVSSTRING_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsnameq_1_svc;
		break;

	case RVSGLT:
		xdr_argument = xdr_RVS1INT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsglt_1_svc;
		break;

	case RVSXYN:
		xdr_argument = xdr_RVSXYN_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsxyn_1_svc;
		break;

	case RVSXYNT:
		xdr_argument = xdr_RVSXYNT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsxynt_1_svc;
		break;

	case RVSXN:
		xdr_argument = xdr_RVSXN_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsxn_1_svc;
		break;

	case RVSXNT:
		xdr_argument = xdr_RVSXNT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsxnt_1_svc;
		break;

	case RVSSXYNT:
		xdr_argument = xdr_RVSSXYNT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvssxynt_1_svc;
		break;

	case RVSMXYNT:
		xdr_argument = xdr_RVSMXYNT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsmxynt_1_svc;
		break;

	case RVSMXY1:
		xdr_argument = xdr_RVSMXY1_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsmxy1_1_svc;
		break;

	case RVSGNXYNI:
		xdr_argument = xdr_RVSGNXYNI_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsgnxyni_1_svc;
		break;

	case RVSNSCT:
		xdr_argument = xdr_RVSNSCT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsnsct_1_svc;
		break;

	case RVSGXYNI:
		xdr_argument = xdr_RVSGXYNI_args;
		xdr_result = xdr_rget_xyvec0_res;
		local = (char *(*)()) rvsgxyni_1_svc;
		break;

	case RVSGETPARAMETERN:
		xdr_argument = xdr_RVSGETPARAMETERN_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsgetparametern_1_svc;
		break;

	case RVSGETLXYN:
		xdr_argument = xdr_RVSGETLXYN_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsgetlxyn_1_svc;
		break;

	case RVSGXYNALL:
		xdr_argument = xdr_RVSGETLXYN_args;
		xdr_result = xdr_rget_xyalldata0_res;
		local = (char *(*)()) rvsgxynall_1_svc;
		break;

	case RVSXYTAGNT:
		xdr_argument = xdr_RVSXYTAGNT_args;
		xdr_result = xdr_int;
		local = (char *(*)()) rvsxytagnt_1_svc;
		break;

	case RVSKILLALL:
		xdr_argument = xdr_void;
		xdr_result = xdr_int;
		local = (char *(*)()) rvskillall_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvcdirty = 0;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvcdirty = 0;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvcdirty = 0;
	return;
}



int
main(argc, argv)
int argc;
char *argv[];
{
	SVCXPRT *transp = NULL;
	int sock;
	int proto = 0;
	struct sockaddr_in saddr;
	int asize = sizeof (saddr);

	if (getsockname(0, (struct sockaddr *)&saddr, &asize) == 0) {
		int ssize = sizeof (int);

		if (saddr.sin_family != AF_INET)
			exit(1);
		if (getsockopt(0, SOL_SOCKET, SO_TYPE,
				(char *)&_rpcfdtype, &ssize) == -1)
			exit(1);
		sock = 0;
		_rpcpmstart = 1;
		proto = 0;
		openlog("rvs", LOG_PID, LOG_DAEMON);
	} else {
#ifndef RPC_SVC_FG
		int size;
		int pid, i;

		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		size = getdtablesize();
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/console", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		i = open("/dev/tty", 2);
		if (i >= 0) {
			(void) ioctl(i, TIOCNOTTY, (char *)NULL);
			(void) close(i);
		}
		openlog("rvs", LOG_PID, LOG_DAEMON);
#endif
		sock = RPC_ANYSOCK;
		(void) pmap_unset(RVS, RVSVERS);
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_DGRAM)) {
		transp = svcudp_create(sock);
		if (transp == NULL) {
			_msgout("cannot create udp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_UDP;
		if (!svc_register(transp, RVS, RVSVERS, rvs_1, proto)) {
			_msgout("unable to register (RVS, RVSVERS, udp).");
			exit(1);
		}
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_STREAM)) {
		if (_rpcpmstart)
			transp = svcfd_create(sock, 0, 0);
		else
			transp = svctcp_create(sock, 0, 0);
		if (transp == NULL) {
			_msgout("cannot create tcp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_TCP;
		if (!svc_register(transp, RVS, RVSVERS, rvs_1, proto)) {
			_msgout("unable to register (RVS, RVSVERS, tcp).");
			exit(1);
		}
	}

	if (transp == (SVCXPRT *)NULL) {
		_msgout("could not create a handle");
		exit(1);
	}
	if (_rpcpmstart) {
		(void) signal(SIGALRM, (void(*)()) closedown);
		(void) alarm(_RPCSVC_CLOSEDOWN);
	}
	svc_run();
	_msgout("svc_run returned");
	exit(1);
	/* NOTREACHED */
}
