/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rvs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include <stdlib.h>

static void
rvs_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		RVSSTRING_args rvsopen_1_arg;
		RVSXY1_args rvsxy1_1_arg;
		RVSXY2_args rvsxy2_1_arg;
		RVS1INT_args rvsclose_1_arg;
		RVS1INT_args rvsstatus_1_arg;
		RVS2INT_args rvssetmaxlxy_1_arg;
		RVS2INT_args rvsgetparameter_1_arg;
		RVS3INT_args rvssetparameter_1_arg;
		RVS2INT_args rvssetaf_1_arg;
		RVS1INT_args rvssetthin_1_arg;
		RVSSTRING_args rvsnameq_1_arg;
		RVS1INT_args rvsglt_1_arg;
		RVSXYN_args rvsxyn_1_arg;
		RVSXYNT_args rvsxynt_1_arg;
		RVSXN_args rvsxn_1_arg;
		RVSXNT_args rvsxnt_1_arg;
		RVSSXYNT_args rvssxynt_1_arg;
		RVSMXYNT_args rvsmxynt_1_arg;
		RVSMXY1_args rvsmxy1_1_arg;
		RVSGNXYNI_args rvsgnxyni_1_arg;
		RVSNSCT_args rvsnsct_1_arg;
		RVSGXYNI_args rvsgxyni_1_arg;
		RVSGETPARAMETERN_args rvsgetparametern_1_arg;
		RVSGETLXYN_args rvsgetlxyn_1_arg;
		RVSGETLXYN_args rvsgxynall_1_arg;
		RVSXYTAGNT_args rvsxytagnt_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RVSCONNECT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsconnect_1_svc;
		break;

	case RVSOPEN:
		_xdr_argument = (xdrproc_t) xdr_RVSSTRING_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsopen_1_svc;
		break;

	case RVSXY1:
		_xdr_argument = (xdrproc_t) xdr_RVSXY1_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsxy1_1_svc;
		break;

	case RVSXY2:
		_xdr_argument = (xdrproc_t) xdr_RVSXY2_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsxy2_1_svc;
		break;

	case RVSCLOSE:
		_xdr_argument = (xdrproc_t) xdr_RVS1INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsclose_1_svc;
		break;

	case RVSHANG:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvshang_1_svc;
		break;

	case RVSSTATUS:
		_xdr_argument = (xdrproc_t) xdr_RVS1INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsstatus_1_svc;
		break;

	case RVSGETVSPID:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsgetvspid_1_svc;
		break;

	case RVSRESET:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsreset_1_svc;
		break;

	case RVSSETMAXLXY:
		_xdr_argument = (xdrproc_t) xdr_RVS2INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvssetmaxlxy_1_svc;
		break;

	case RVSGETPARAMETER:
		_xdr_argument = (xdrproc_t) xdr_RVS2INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsgetparameter_1_svc;
		break;

	case RVSSETPARAMETER:
		_xdr_argument = (xdrproc_t) xdr_RVS3INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvssetparameter_1_svc;
		break;

	case RVSSETAF:
		_xdr_argument = (xdrproc_t) xdr_RVS2INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvssetaf_1_svc;
		break;

	case RVSSETTHIN:
		_xdr_argument = (xdrproc_t) xdr_RVS1INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvssetthin_1_svc;
		break;

	case RVSNAMEQ:
		_xdr_argument = (xdrproc_t) xdr_RVSSTRING_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsnameq_1_svc;
		break;

	case RVSGLT:
		_xdr_argument = (xdrproc_t) xdr_RVS1INT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsglt_1_svc;
		break;

	case RVSXYN:
		_xdr_argument = (xdrproc_t) xdr_RVSXYN_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsxyn_1_svc;
		break;

	case RVSXYNT:
		_xdr_argument = (xdrproc_t) xdr_RVSXYNT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsxynt_1_svc;
		break;

	case RVSXN:
		_xdr_argument = (xdrproc_t) xdr_RVSXN_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsxn_1_svc;
		break;

	case RVSXNT:
		_xdr_argument = (xdrproc_t) xdr_RVSXNT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsxnt_1_svc;
		break;

	case RVSSXYNT:
		_xdr_argument = (xdrproc_t) xdr_RVSSXYNT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvssxynt_1_svc;
		break;

	case RVSMXYNT:
		_xdr_argument = (xdrproc_t) xdr_RVSMXYNT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsmxynt_1_svc;
		break;

	case RVSMXY1:
		_xdr_argument = (xdrproc_t) xdr_RVSMXY1_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsmxy1_1_svc;
		break;

	case RVSGNXYNI:
		_xdr_argument = (xdrproc_t) xdr_RVSGNXYNI_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsgnxyni_1_svc;
		break;

	case RVSNSCT:
		_xdr_argument = (xdrproc_t) xdr_RVSNSCT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsnsct_1_svc;
		break;

	case RVSGXYNI:
		_xdr_argument = (xdrproc_t) xdr_RVSGXYNI_args;
		_xdr_result = (xdrproc_t) xdr_rget_xyvec0_res;
		local = (char *(*)(char *, struct svc_req *)) rvsgxyni_1_svc;
		break;

	case RVSGETPARAMETERN:
		_xdr_argument = (xdrproc_t) xdr_RVSGETPARAMETERN_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsgetparametern_1_svc;
		break;

	case RVSGETLXYN:
		_xdr_argument = (xdrproc_t) xdr_RVSGETLXYN_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsgetlxyn_1_svc;
		break;

	case RVSGXYNALL:
		_xdr_argument = (xdrproc_t) xdr_RVSGETLXYN_args;
		_xdr_result = (xdrproc_t) xdr_rget_xyalldata0_res;
		local = (char *(*)(char *, struct svc_req *)) rvsgxynall_1_svc;
		break;

	case RVSXYTAGNT:
		_xdr_argument = (xdrproc_t) xdr_RVSXYTAGNT_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvsxytagnt_1_svc;
		break;

	case RVSKILLALL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rvskillall_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RVS, RVSVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RVS, RVSVERS, rvs_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RVS, RVSVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RVS, RVSVERS, rvs_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RVS, RVSVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
