# Generated automatically from Makefile.in by configure.
.IGNORE:

SHELL = /bin/sh

prefix = /home/dave/CLAM
bindir = $(prefix)/bin
includedir = $(prefix)/include
libdir = $(prefix)/lib

prefix  = /home/dave/CLAM

BBH_SYSTEM = LINUX_IA32

AR     = ar
RANLIB = ranlib

F77_TRANSFORM = touch

LIBS       = 
LDFLAGS    = -L/home/dave/CLAM/lib -L.

CC       = icc
CFLAGS   = -c -O3 -axK -tpp6
CPPFLAGS = -I/home/dave/CLAM/include

CC_COMP  = $(CC) $(CFLAGS) $(CPPFLAGS)
CC_LOAD  = $(CC) $(LDFLAGS)

F77      = ifc
F77FLAGS = -O3 -axK -tpp6 -w90 -w95 -cm -Vaxlib

F77_COMP   = $(F77) -c $(F77FLAGS) 
F77_LOAD   = $(F77) $(F77FLAGS) $(LDFLAGS)

.f.o:
	$(F77_COMP) $*.f 

.c.o:
	$(CC_COMP) $*.c

LIBS     = libodepack.a

install: all
	if test ! -d $(libdir); then\
		mkdir -p $(libdir);\
	fi
	cp $(LIBS) $(libdir)

all: $(LIBS)

LIB_ODEPACK_OBJ =\
adjlr.o\
aigbt.o\
ainvg.o\
blkdta000.o\
bnorm.o\
cdrv.o\
cfode.o\
cntnzu.o\
decbt.o\
d1mach.o\
ewset.o\
fnorm.o\
intdy.o\
iprep.o\
jgroup.o\
lsoda.o\
lsodar.o\
lsode.o\
lsodes.o\
lsodi.o\
lsoibt.o\
md.o\
mdi.o\
mdm.o\
mdp.o\
mdu.o\
nnfc.o\
nnsc.o\
nntc.o\
nroc.o\
nsfc.o\
odrv.o\
pjibt.o\
prep.o\
prepj.o\
prepji.o\
prja.o\
prjs.o\
rchek.o\
roots.o\
slsbt.o\
slss.o\
solbt.o\
solsy.o\
srcar.o\
srcma.o\
srcms.o\
srcom.o\
sro.o\
stoda.o\
stode.o\
stodi.o\
vmnorm.o\
vnorm.o\
xerrwv.o\
xsetf.o\
xsetun.o

libodepack.a: $(LIB_ODEPACK_OBJ)
	$(AR) r libodepack.a $(LIB_ODEPACK_OBJ)

########################################################################
# Clean-up
########################################################################
clean:
	/bin/rm *.o 
	/bin/rm *.a
	/bin/rm  Makefile config.cache config.log config.status
